name: caixin-daily
on:
schedule:
- cron: "0 0 * * *"
workflow_dispatch:
jobs:
push:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
- name: push
env:
BARK_URL: ${{ secrets.BARK_URL }}
run: python3 caixin_push.py
